name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v1.0.1, etc.
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get version from git tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Building version ${VERSION}"
    
    - name: Create extension package
      run: |
        mkdir -p dist
        zip -r dist/loops-extension-v${{ steps.version.outputs.VERSION }}.zip . \
          -x "*.git*" \
          -x "node_modules/*" \
          -x "dist/*" \
          -x "scripts/*" \
          -x "*.sh" \
          -x "*.md" \
          -x "package*.json" \
          -x "eslint.config.js" \
          -x ".prettierrc" \
          -x ".husky/*" \
          -x "test-*.js" \
          -x ".github/*" \
          -x "IDEAS.md" \
          -x "TEST.md" \
          -x "spec.md" \
          -x "*.log" \
          -x ".DS_Store" \
          -x "Thumbs.db"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Loops Extension v${{ steps.version.outputs.VERSION }}"
        body: |
          ## 🚀 Loops Extension v${{ steps.version.outputs.VERSION }}
          
          ### 📦 Installation
          1. Download `loops-extension-v${{ steps.version.outputs.VERSION }}.zip` from the assets below
          2. Open Chrome and go to `chrome://extensions/`
          3. Enable "Developer mode" 
          4. Click "Load unpacked" and select the extracted folder
          
          ### ⌨️ Quick Start
          - **Alt+R** - Save tab to Read Later
          - **Alt+T** - Save tab to Tasks  
          - **Alt+Shift+R/T** - Save with notes (manual setup required)
          
          ### 🔧 Features
          - Cross-device Chrome sync
          - GitHub Gists integration for unlimited storage
          - Smart tab management with bulk operations
          - Auto-save settings with floating indicators
          
          Ready for Chrome Web Store submission! 🎉
        files: |
          dist/loops-extension-v${{ steps.version.outputs.VERSION }}.zip
        draft: false
        prerelease: false